# Generated by Django 4.0.6 on 2022-07-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_call_back_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_back',
            name='test_field',
        ),
    ]
