# Generated by Django 4.0.6 on 2022-07-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_call_back_test_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_news',
            fields=[
                ('category_name', models.CharField(max_length=100)),
                ('category_id', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.category_news'),
            preserve_default=False,
        ),
    ]
