# Generated by Django 4.0.6 on 2022-07-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_call_back_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_news',
            name='category_name_en',
            field=models.CharField(default='all', max_length=130),
            preserve_default=False,
        ),
    ]
